Config extractor and config service enhancement (#29)
* fix(test): use single thread for testing

* refactor: config extractor and config service

* chore: remove unuse crypto functions

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,15 @@
+echo "=== Format EErrorCode  ==="
+npm run enum:convert:error-response
+
 echo "=== Typecheck  ==="
 npm run typecheck || exit 1
 
 echo "=== Lint fix ==="
 npm run lint:fix || exit 1
 
-echo "=== Format EErrorCode  ==="
-npm run enum:convert:error-response
+export RUN_FULL_TEST=true
+echo "set RUN_FULL_TEST=TRUE"
 
-npm run test:all || exit 1
-
-npm run dotenv:pull
-npm run dotenv:push
+npm run test || exit 1
 
 git add .
